/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c2c6d4",
        "on-tertiary-fixed": "#141d23",
        "background": "#f7f9ff",
        "on-tertiary-container": "#c8d1da",
        "on-surface-variant": "#424752",
        "primary": "#003f87",
        "tertiary-fixed": "#dbe4ed",
        "primary-fixed": "#d7e2ff",
        "secondary-container": "#e1e3e4",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#acc7ff",
        "on-primary-fixed-variant": "#004491",
        "on-secondary-container": "#626566",
        "outline": "#727784",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eef1f6",
        "surface-container": "#ebeef3",
        "tertiary-container": "#515a62",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#181c20",
        "on-tertiary-fixed-variant": "#3f484f",
        "tertiary-fixed-dim": "#bfc8d0",
        "surface-container-highest": "#e0e3e8",
        "surface-variant": "#e0e3e8",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f1f4f9",
        "on-secondary-fixed-variant": "#454748",
        "inverse-surface": "#2d3135",
        "error": "#ba1a1a",
        "secondary": "#5c5f60",
        "surface": "#f7f9ff",
        "surface-container-high": "#e5e8ee",
        "primary-container": "#0056b3",
        "surface-dim": "#d7dadf",
        "secondary-fixed-dim": "#c5c7c8",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#191c1d",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e1e3e4",
        "inverse-primary": "#acc7ff",
        "on-surface": "#181c20",
        "tertiary": "#3a434a",
        "surface-tint": "#115cb9",
        "on-primary-container": "#bbd0ff",
        "surface-bright": "#f7f9ff",
        "on-primary-fixed": "#001a40"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "base": "8px",
        "lg": "24px",
        "md": "16px",
        "xxl": "48px",
        "sidebar-width": "280px",
        "sm": "8px",
        "container-max": "1440px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
